services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.9

    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app_password
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
